# Site settings
title: Techno-OH | A technical blog
description: "My technical experience in words!"
url: "shekharsingh1987.github.io"
author:
  name: "Shekhar Kumar"
  email: "shekharsingh_1987@yahoo.com"
  url: "shekharsingh1987.github.io"

# Build settings
baseurl: /blogs # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Custom variables
version: "1.1.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
